using System;
using ZP.CSharp.Music;
namespace ZP.CSharp.Music
{
    public class LaMarseillaise : IPieceProvider
    {
        public static Piece GetPiece()
        {
            return new Piece(
                new Voice(
                    new Note(120, Pitch.G4, Duration.SemiQuaver),
                    new Note(120, Pitch.G4, Duration.SemiQuaver | Duration.Quaver),
                    new Note(120, Pitch.G4, Duration.SemiQuaver),
                    new Note(120, Pitch.C5),
                    new Note(120, Pitch.C5),
                    new Note(120, Pitch.D5),
                    new Note(120, Pitch.D5),
                    new Note(120, Pitch.G5, Duration.Crotchet | Duration.Quaver),
                    new Note(120, Pitch.E5, Duration.Quaver),
                    new Note(120, Pitch.C5, Duration.SemiQuaver | Duration.Quaver),
                    new Note(120, Pitch.C5, Duration.SemiQuaver),
                    new Note(120, Pitch.E5, Duration.SemiQuaver | Duration.Quaver),
                    new Note(120, Pitch.C5, Duration.SemiQuaver),
                    new Note(120, Pitch.A4),
                    new Note(120, Pitch.F5),
                    new Note(120, Pitch.Rest),
                    new Note(120, Pitch.D5, Duration.SemiQuaver | Duration.Quaver),
                    new Note(120, Pitch.B4, Duration.SemiQuaver),
                    new Note(120, Pitch.C5, Duration.Minim),
                    new Note(120, Pitch.Rest),
                    new Note(120, Pitch.C5, Duration.Quaver | Duration.SemiQuaver),
                    new Note(120, Pitch.D5, Duration.SemiQuaver),
                    new Note(120, Pitch.E5),
                    new Note(120, Pitch.E5, Duration.SemiQuaver | Duration.Quaver),
                    new Note(120, Pitch.E5, Duration.SemiQuaver),
                    new Note(120, Pitch.E5),
                    new Note(120, Pitch.F5, Duration.SemiQuaver | Duration.Quaver),
                    new Note(120, Pitch.E5, Duration.SemiQuaver),
                    new Note(120, Pitch.E5),
                    new Note(120, Pitch.D5),
                    new Note(120, Pitch.Rest),
                    new Note(120, Pitch.D5, Duration.Quaver | Duration.SemiQuaver),
                    new Note(120, Pitch.E5, Duration.SemiQuaver),
                    new Note(120, Pitch.F5),
                    new Note(120, Pitch.F5, Duration.SemiQuaver | Duration.Quaver),
                    new Note(120, Pitch.F5, Duration.SemiQuaver),
                    new Note(120, Pitch.F5),
                    new Note(120, Pitch.G5, Duration.SemiQuaver | Duration.Quaver),
                    new Note(120, Pitch.F5, Duration.SemiQuaver),
                    new Note(120, Pitch.E5, Duration.Minim),
                    new Note(120, Pitch.Rest),
                    new Note(120, Pitch.G5, Duration.Quaver | Duration.SemiQuaver),
                    new Note(120, Pitch.G5, Duration.SemiQuaver),
                    new Note(120, Pitch.G5),
                    new Note(120, Pitch.E5, Duration.Quaver | Duration.SemiQuaver),
                    new Note(120, Pitch.C5, Duration.SemiQuaver),
                    new Note(120, Pitch.G5),
                    new Note(120, Pitch.E5, Duration.Quaver | Duration.SemiQuaver),
                    new Note(120, Pitch.C5, Duration.SemiQuaver),
                    new Note(120, Pitch.G4, Duration.Minim),
                    new Note(120, Pitch.Rest),
                    new Note(120, Pitch.G4, Duration.Quaver | Duration.SemiQuaver),
                    new Note(120, Pitch.B4, Duration.SemiQuaver),
                    new Note(120, Pitch.D5, Duration.Minim),
                    new Note(120, Pitch.F5),
                    new Note(120, Pitch.D5, Duration.Quaver | Duration.SemiQuaver),
                    new Note(120, Pitch.B4, Duration.SemiQuaver),
                    new Note(120, Pitch.C5),
                    new Note(120, Pitch.C5),
                    new Note(120, Pitch.ASharp4),
                    new Note(120, Pitch.Rest),
                    new Note(120, Pitch.A4),
                    new Note(120, Pitch.C5, Duration.Quaver | Duration.SemiQuaver),
                    new Note(120, Pitch.C5, Duration.SemiQuaver),
                    new Note(120, Pitch.C5),
                    new Note(120, Pitch.B4, Duration.Quaver | Duration.SemiQuaver),
                    new Note(120, Pitch.C5, Duration.SemiQuaver),
                    new Note(120, Pitch.D5, Duration.Minim),
                    new Note(120, Pitch.Rest, Duration.Crotchet | Duration.Quaver),
                    new Note(120, Pitch.D5, Duration.Quaver),
                    new Note(120, Pitch.DSharp5, Duration.Crotchet | Duration.Quaver),
                    new Note(120, Pitch.DSharp5, Duration.Quaver),
                    new Note(120, Pitch.DSharp5, Duration.Quaver),
                    new Note(120, Pitch.DSharp5, Duration.Quaver),
                    new Note(120, Pitch.F5, Duration.Quaver | Duration.SemiQuaver),
                    new Note(120, Pitch.G5, Duration.SemiQuaver),
                    new Note(120, Pitch.D5, Duration.Minim),
                    new Note(120, Pitch.Rest),
                    new Note(120, Pitch.DSharp5, Duration.Quaver | Duration.SemiQuaver),
                    new Note(120, Pitch.D5, Duration.SemiQuaver),
                    new Note(120, Pitch.C5),
                    new Note(120, Pitch.C5, Duration.Quaver | Duration.SemiQuaver),
                    new Note(120, Pitch.C5, Duration.SemiQuaver),
                    new Note(120, Pitch.DSharp5),
                    new Note(120, Pitch.D5, Duration.Quaver | Duration.SemiQuaver),
                    new Note(120, Pitch.C5, Duration.SemiQuaver),
                    new Note(120, Pitch.C5),
                    new Note(120, Pitch.B4),
                    new Note(120, Pitch.Rest, Duration.Crotchet | Duration.Quaver | Duration.SemiQuaver),
                    new Note(120, Pitch.G5, Duration.SemiQuaver),
                    new Note(120, Pitch.G5, Duration.Minim | Duration.Quaver),
                    new Note(120, Pitch.G5, Duration.Quaver),
                    new Note(120, Pitch.E5, Duration.Quaver | Duration.SemiQuaver),
                    new Note(120, Pitch.C5, Duration.SemiQuaver),
                    new Note(120, Pitch.D5, Duration.Minim),
                    new Note(120, Pitch.Rest, Duration.Crotchet | Duration.Quaver | Duration.SemiQuaver),
                    new Note(120, Pitch.G5, Duration.SemiQuaver),
                    new Note(120, Pitch.G5, Duration.Minim | Duration.Quaver),
                    new Note(120, Pitch.G5, Duration.Quaver),
                    new Note(120, Pitch.E5, Duration.Quaver | Duration.SemiQuaver),
                    new Note(120, Pitch.C5, Duration.SemiQuaver),
                    new Note(120, Pitch.D5, Duration.Minim),
                    new Note(120, Pitch.Rest),
                    new Note(120, Pitch.G4),
                    new Note(120, Pitch.C5, Duration.Minim),
                    new Note(120, Pitch.Rest),
                    new Note(120, Pitch.C5),
                    new Note(120, Pitch.E5, Duration.Minim),
                    new Note(120, Pitch.Rest, Duration.Minim),
                    new Note(120, Pitch.F5, Duration.Minim),
                    new Note(120, Pitch.G5),
                    new Note(120, Pitch.A5),
                    new Note(120, Pitch.D5, Duration.Minim),
                    new Note(120, Pitch.Rest),
                    new Note(120, Pitch.A5),
                    new Note(120, Pitch.G5, Duration.Minim),
                    new Note(120, Pitch.Rest, Duration.Quaver),
                    new Note(120, Pitch.E5, Duration.SemiQuaver),
                    new Note(120, Pitch.F5, Duration.Quaver | Duration.SemiQuaver),
                    new Note(120, Pitch.D5, Duration.SemiQuaver),
                    new Note(120, Pitch.C5, Duration.Minim)
                )
            );
        }
    }
}